import { CDN_URL_1, CDN_URL_10, CDN_URL_11, CDN_URL_12, CDN_URL_13, CDN_URL_14, CDN_URL_15, CDN_URL_16, CDN_URL_17, CDN_URL_18, CDN_URL_19, CDN_URL_2, CDN_URL_20, CDN_URL_3, CDN_URL_4, CDN_URL_5, CDN_URL_6, CDN_URL_7, CDN_URL_8, CDN_URL_9 } from "./constants";

const resList = [
  {
    id: "1",
    resName: "Meghana Foods",
    cuisine: "North Indian, South Indian, Asian",
    img: CDN_URL_1,
    averageRating: "4.4",
    duration: "38",
  },
  {
    id: "2",
    resName: "KFC",
    cuisine: "Burgers, Fast Food, Rolls & Wraps",
    img: CDN_URL_2,
    averageRating: "4.4",
    duration: "35",
  },
  {
    id: "3",
    resName: "Theobroma",
    cuisine: "Desserts, Beverages",
    img: CDN_URL_3,
    averageRating: "4.7",
    duration: "25",
  },
  {
    id: "4",
    resName: "Empire Restaurant",
    cuisine: "North Indian, Chinese",
    img: CDN_URL_4,
    averageRating: "4.2",
    duration: "30",
  },
  {
    id: "5",
    resName: "Truffles",
    cuisine: "American, Fast Food",
    img: CDN_URL_5,
    averageRating: "2.5",
    duration: "28",
  },
  {
    id: "6",
    resName: "Domino's Pizza",
    cuisine: "Pizzas, Italian",
    img: CDN_URL_6,
    averageRating: "1.0",
    duration: "22",
  },
  {
    id: "7",
    resName: "Biriyani Blues",
    cuisine: "Biryani, Mughlai",
    img: CDN_URL_7,
    averageRating: "3.3",
    duration: "27",
  },
  {
    id: "8",
    resName: "A2B - Adyar Ananda Bhavan",
    cuisine: "South Indian, Sweets",
    img: CDN_URL_8,
    averageRating: "3.1",
    duration: "20",
  },
  {
    id: "9",
    resName: "Chinita",
    cuisine: "Mexican",
    img: CDN_URL_9,
    averageRating: "4.6",
    duration: "26",
  },
  {
    id: "10",
    resName: "Corner House",
    cuisine: "Ice Creams, Desserts",
    img: CDN_URL_10,
    averageRating: "4.8",
    duration: "18",
  },
  {
    id: "11",
    resName: "Wendy’s",
    cuisine: "Fast Food, Burgers",
    img: CDN_URL_11,
    averageRating: "4.0",
    duration: "24",
  },
  {
    id: "12",
    resName: "Pista House",
    cuisine: "Hyderabadi, Biryani",
    img: CDN_URL_12,
    averageRating: "4.3",
    duration: "29",
  },
  {
    id: "13",
    resName: "Smoor",
    cuisine: "Bakery, Desserts",
    img: CDN_URL_13,
    averageRating: "4.5",
    duration: "19",
  },
  {
    id: "14",
    resName: "Chai Point",
    cuisine: "Beverages, Snacks",
    img: CDN_URL_14,
    averageRating: "4.2",
    duration: "21",
  },
  {
    id: "15",
    resName: "Little Italy",
    cuisine: "Italian, Pizza, Pasta",
    img: CDN_URL_15,
    averageRating: "4.6",
    duration: "33",
  },
  {
    id: "16",
    resName: "Taco Bell",
    cuisine: "Mexican, Fast Food",
    img: CDN_URL_16,
    averageRating: "4.1",
    duration: "23",
  },
  {
    id: "17",
    resName: "Rajdhani Thali",
    cuisine: "Rajasthani, Gujarati",
    img: CDN_URL_17,
    averageRating: "4.4",
    duration: "32",
  },
  {
    id: "18",
    resName: "Nandhana Palace",
    cuisine: "Andhra, Biryani",
    img: CDN_URL_18,
    averageRating: "4.3",
    duration: "31",
  },
  {
    id: "19",
    resName: "Saffron Spice",
    cuisine: "North Indian, Tandoor",
    img: CDN_URL_19,
    averageRating: "4.2",
    duration: "34",
  },
  {
    id: "20",
    resName: "Beijing Bites",
    cuisine: "Chinese, Asian",
    img: CDN_URL_20,
    averageRating: "4.0",
    duration: "30",
  },
];



export default resList;